
package InterfazPanel;

import ilibreriadivisas.ConversorDivisas;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author angel
 */
public class IPaneldivisas extends javax.swing.JPanel {

    /**
     * Creates new form husdfhudshufdshuf
     */
    public IPaneldivisas() {
        initComponents();
        cargarDivisas();
        inicializarEventos();
    }

    
    
    
    
    // Inicializa listeners y eventos
    private void inicializarEventos() {
        btnConvertir.addActionListener(e -> realizarConversion());
    }

    
    
    
    
    // Lógica de conversión
    private void realizarConversion() {
        try {
            String divisaOrigen = cmbDivOrigen.getSelectedItem().toString();
            String divisaDestino = cmbDivDestino.getSelectedItem().toString();
            String textoMonto = txtMonto.getText().trim();

            if (textoMonto.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Por favor ingresa un monto a convertir.");
                return;
            }

            double monto = Double.parseDouble(textoMonto);
            if (monto < 0) {
                JOptionPane.showMessageDialog(this, "El monto no puede ser negativo.");
                return;
            }

            double tasa = obtenerTasaConversion(divisaOrigen, divisaDestino);
            double resultado = tasa * monto;
            DecimalFormat df = new DecimalFormat("#.##");

            lblMonedaOrigen.setText("Moneda de origen: " + divisaOrigen);
            lblResultado.setText("Equivalencia en " + divisaDestino + ": " + df.format(resultado));

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Ingresa un número válido.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
            ex.printStackTrace();
        }
    }

    
    
    
    
    // Carga las divisas al comboBox
    private void cargarDivisas() {
        try {
            String[] divisas = ConversorDivisas.simboloMonetario();
            cmbDivOrigen.removeAllItems();
            cmbDivDestino.removeAllItems();
            for (String divisa : divisas) {
                cmbDivOrigen.addItem(divisa);
                cmbDivDestino.addItem(divisa);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar divisas: " + ex.getMessage());
        }
    }
    
    
    
    

    // Obtiene la tasa de conversión
    private double obtenerTasaConversion(String origen, String destino) throws Exception {
        if (origen.equals(destino)) return 1.0;
        return ConversorDivisas.origenaDestino(origen, destino);
    }
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbDivOrigen = new javax.swing.JComboBox<>();
        cmbDivDestino = new javax.swing.JComboBox<>();
        txtMonto = new javax.swing.JTextField();
        btnConvertir = new javax.swing.JButton();
        lblMonedaOrigen = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        cmbDivOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbDivOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDivOrigenActionPerformed(evt);
            }
        });

        cmbDivDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoActionPerformed(evt);
            }
        });

        btnConvertir.setText("Convertir");

        lblMonedaOrigen.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        lblResultado.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jLabel1.setText("Divisa Origen");

        jLabel2.setText("Divisa Destino");

        jLabel3.setFont(new java.awt.Font("Segoe Script", 0, 36)); // NOI18N
        jLabel3.setText("Conversor de divisas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(53, 53, 53)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblMonedaOrigen, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                                        .addComponent(lblResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(322, 322, 322)
                                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(97, 97, 97))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbDivDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbDivOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(223, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbDivOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbDivDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(lblMonedaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoActionPerformed

    private void cmbDivOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDivOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDivOrigenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvertir;
    private javax.swing.JComboBox<String> cmbDivDestino;
    private javax.swing.JComboBox<String> cmbDivOrigen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblMonedaOrigen;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables
}
